// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:User.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// User TABLE
class TableUser extends SqfEntityTableBase {
  TableUser() {
    // declare properties of EntityTable
    tableName = 'user';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('picture_source', DbType.text,
          defaultValue: 'network'),
      SqfEntityFieldBase('email', DbType.text),
      SqfEntityFieldBase('title', DbType.text),
      SqfEntityFieldBase('first', DbType.text),
      SqfEntityFieldBase('gender', DbType.text),
      SqfEntityFieldBase('last', DbType.text),
      SqfEntityFieldBase('street_number', DbType.text),
      SqfEntityFieldBase('street_name', DbType.text),
      SqfEntityFieldBase('location_city', DbType.text),
      SqfEntityFieldBase('location_state', DbType.text),
      SqfEntityFieldBase('location_contry', DbType.text),
      SqfEntityFieldBase('coordinate_lat', DbType.text),
      SqfEntityFieldBase('coordinate_long', DbType.text),
      SqfEntityFieldBase('date_of_birth', DbType.numeric),
      SqfEntityFieldBase('age', DbType.numeric),
      SqfEntityFieldBase('registration_age', DbType.numeric),
      SqfEntityFieldBase('date_of_registration', DbType.numeric),
      SqfEntityFieldBase('phone', DbType.text),
      SqfEntityFieldBase('cell', DbType.text),
      SqfEntityFieldBase('id_value', DbType.text),
      SqfEntityFieldBase('id_name', DbType.text),
      SqfEntityFieldBase('picture_path', DbType.text),
      SqfEntityFieldBase('nat', DbType.text),
      SqfEntityFieldBase('timezone_value', DbType.text),
      SqfEntityFieldBase('timezone_description', DbType.text),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableUser();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class FlutterTestModel extends SqfEntityModelProvider {
  FlutterTestModel() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    preSaveAction = myDbModel.preSaveAction;
    logFunction = myDbModel.logFunction;
    databaseTables = [
      TableUser.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = myDbModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region User
class User extends TableBase {
  User(
      {this.id,
      this.picture_source,
      this.email,
      this.title,
      this.first,
      this.gender,
      this.last,
      this.street_number,
      this.street_name,
      this.location_city,
      this.location_state,
      this.location_contry,
      this.coordinate_lat,
      this.coordinate_long,
      this.date_of_birth,
      this.age,
      this.registration_age,
      this.date_of_registration,
      this.phone,
      this.cell,
      this.id_value,
      this.id_name,
      this.picture_path,
      this.nat,
      this.timezone_value,
      this.timezone_description}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  User.withFields(
      this.picture_source,
      this.email,
      this.title,
      this.first,
      this.gender,
      this.last,
      this.street_number,
      this.street_name,
      this.location_city,
      this.location_state,
      this.location_contry,
      this.coordinate_lat,
      this.coordinate_long,
      this.date_of_birth,
      this.age,
      this.registration_age,
      this.date_of_registration,
      this.phone,
      this.cell,
      this.id_value,
      this.id_name,
      this.picture_path,
      this.nat,
      this.timezone_value,
      this.timezone_description) {
    _setDefaultValues();
  }
  User.withId(
      this.id,
      this.picture_source,
      this.email,
      this.title,
      this.first,
      this.gender,
      this.last,
      this.street_number,
      this.street_name,
      this.location_city,
      this.location_state,
      this.location_contry,
      this.coordinate_lat,
      this.coordinate_long,
      this.date_of_birth,
      this.age,
      this.registration_age,
      this.date_of_registration,
      this.phone,
      this.cell,
      this.id_value,
      this.id_name,
      this.picture_path,
      this.nat,
      this.timezone_value,
      this.timezone_description) {
    _setDefaultValues();
  }
  // fromMap v2.0
  User.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['picture_source'] != null) {
      picture_source = o['picture_source'].toString();
    }
    if (o['email'] != null) {
      email = o['email'].toString();
    }
    if (o['title'] != null) {
      title = o['title'].toString();
    }
    if (o['first'] != null) {
      first = o['first'].toString();
    }
    if (o['gender'] != null) {
      gender = o['gender'].toString();
    }
    if (o['last'] != null) {
      last = o['last'].toString();
    }
    if (o['street_number'] != null) {
      street_number = o['street_number'].toString();
    }
    if (o['street_name'] != null) {
      street_name = o['street_name'].toString();
    }
    if (o['location_city'] != null) {
      location_city = o['location_city'].toString();
    }
    if (o['location_state'] != null) {
      location_state = o['location_state'].toString();
    }
    if (o['location_contry'] != null) {
      location_contry = o['location_contry'].toString();
    }
    if (o['coordinate_lat'] != null) {
      coordinate_lat = o['coordinate_lat'].toString();
    }
    if (o['coordinate_long'] != null) {
      coordinate_long = o['coordinate_long'].toString();
    }
    if (o['date_of_birth'] != null) {
      date_of_birth = int.tryParse(o['date_of_birth'].toString());
    }
    if (o['age'] != null) {
      age = int.tryParse(o['age'].toString());
    }
    if (o['registration_age'] != null) {
      registration_age = int.tryParse(o['registration_age'].toString());
    }
    if (o['date_of_registration'] != null) {
      date_of_registration = int.tryParse(o['date_of_registration'].toString());
    }
    if (o['phone'] != null) {
      phone = o['phone'].toString();
    }
    if (o['cell'] != null) {
      cell = o['cell'].toString();
    }
    if (o['id_value'] != null) {
      id_value = o['id_value'].toString();
    }
    if (o['id_name'] != null) {
      id_name = o['id_name'].toString();
    }
    if (o['picture_path'] != null) {
      picture_path = o['picture_path'].toString();
    }
    if (o['nat'] != null) {
      nat = o['nat'].toString();
    }
    if (o['timezone_value'] != null) {
      timezone_value = o['timezone_value'].toString();
    }
    if (o['timezone_description'] != null) {
      timezone_description = o['timezone_description'].toString();
    }
  }
  // FIELDS (User)
  int? id;
  String? picture_source;
  String? email;
  String? title;
  String? first;
  String? gender;
  String? last;
  String? street_number;
  String? street_name;
  String? location_city;
  String? location_state;
  String? location_contry;
  String? coordinate_lat;
  String? coordinate_long;
  int? date_of_birth;
  int? age;
  int? registration_age;
  int? date_of_registration;
  String? phone;
  String? cell;
  String? id_value;
  String? id_name;
  String? picture_path;
  String? nat;
  String? timezone_value;
  String? timezone_description;

  // end FIELDS (User)

  static const bool _softDeleteActivated = false;
  UserManager? __mnUser;

  UserManager get _mnUser {
    return __mnUser = __mnUser ?? UserManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (picture_source != null || !forView) {
      map['picture_source'] = picture_source;
    }
    if (email != null || !forView) {
      map['email'] = email;
    }
    if (title != null || !forView) {
      map['title'] = title;
    }
    if (first != null || !forView) {
      map['first'] = first;
    }
    if (gender != null || !forView) {
      map['gender'] = gender;
    }
    if (last != null || !forView) {
      map['last'] = last;
    }
    if (street_number != null || !forView) {
      map['street_number'] = street_number;
    }
    if (street_name != null || !forView) {
      map['street_name'] = street_name;
    }
    if (location_city != null || !forView) {
      map['location_city'] = location_city;
    }
    if (location_state != null || !forView) {
      map['location_state'] = location_state;
    }
    if (location_contry != null || !forView) {
      map['location_contry'] = location_contry;
    }
    if (coordinate_lat != null || !forView) {
      map['coordinate_lat'] = coordinate_lat;
    }
    if (coordinate_long != null || !forView) {
      map['coordinate_long'] = coordinate_long;
    }
    if (date_of_birth != null || !forView) {
      map['date_of_birth'] = date_of_birth;
    }
    if (age != null || !forView) {
      map['age'] = age;
    }
    if (registration_age != null || !forView) {
      map['registration_age'] = registration_age;
    }
    if (date_of_registration != null || !forView) {
      map['date_of_registration'] = date_of_registration;
    }
    if (phone != null || !forView) {
      map['phone'] = phone;
    }
    if (cell != null || !forView) {
      map['cell'] = cell;
    }
    if (id_value != null || !forView) {
      map['id_value'] = id_value;
    }
    if (id_name != null || !forView) {
      map['id_name'] = id_name;
    }
    if (picture_path != null || !forView) {
      map['picture_path'] = picture_path;
    }
    if (nat != null || !forView) {
      map['nat'] = nat;
    }
    if (timezone_value != null || !forView) {
      map['timezone_value'] = timezone_value;
    }
    if (timezone_description != null || !forView) {
      map['timezone_description'] = timezone_description;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (picture_source != null || !forView) {
      map['picture_source'] = picture_source;
    }
    if (email != null || !forView) {
      map['email'] = email;
    }
    if (title != null || !forView) {
      map['title'] = title;
    }
    if (first != null || !forView) {
      map['first'] = first;
    }
    if (gender != null || !forView) {
      map['gender'] = gender;
    }
    if (last != null || !forView) {
      map['last'] = last;
    }
    if (street_number != null || !forView) {
      map['street_number'] = street_number;
    }
    if (street_name != null || !forView) {
      map['street_name'] = street_name;
    }
    if (location_city != null || !forView) {
      map['location_city'] = location_city;
    }
    if (location_state != null || !forView) {
      map['location_state'] = location_state;
    }
    if (location_contry != null || !forView) {
      map['location_contry'] = location_contry;
    }
    if (coordinate_lat != null || !forView) {
      map['coordinate_lat'] = coordinate_lat;
    }
    if (coordinate_long != null || !forView) {
      map['coordinate_long'] = coordinate_long;
    }
    if (date_of_birth != null || !forView) {
      map['date_of_birth'] = date_of_birth;
    }
    if (age != null || !forView) {
      map['age'] = age;
    }
    if (registration_age != null || !forView) {
      map['registration_age'] = registration_age;
    }
    if (date_of_registration != null || !forView) {
      map['date_of_registration'] = date_of_registration;
    }
    if (phone != null || !forView) {
      map['phone'] = phone;
    }
    if (cell != null || !forView) {
      map['cell'] = cell;
    }
    if (id_value != null || !forView) {
      map['id_value'] = id_value;
    }
    if (id_name != null || !forView) {
      map['id_name'] = id_name;
    }
    if (picture_path != null || !forView) {
      map['picture_path'] = picture_path;
    }
    if (nat != null || !forView) {
      map['nat'] = nat;
    }
    if (timezone_value != null || !forView) {
      map['timezone_value'] = timezone_value;
    }
    if (timezone_description != null || !forView) {
      map['timezone_description'] = timezone_description;
    }

    return map;
  }

  /// This method returns Json String [User]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [User]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [
      picture_source,
      email,
      title,
      first,
      gender,
      last,
      street_number,
      street_name,
      location_city,
      location_state,
      location_contry,
      coordinate_lat,
      coordinate_long,
      date_of_birth,
      age,
      registration_age,
      date_of_registration,
      phone,
      cell,
      id_value,
      id_name,
      picture_path,
      nat,
      timezone_value,
      timezone_description
    ];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [
      id,
      picture_source,
      email,
      title,
      first,
      gender,
      last,
      street_number,
      street_name,
      location_city,
      location_state,
      location_contry,
      coordinate_lat,
      coordinate_long,
      date_of_birth,
      age,
      registration_age,
      date_of_registration,
      phone,
      cell,
      id_value,
      id_name,
      picture_path,
      nat,
      timezone_value,
      timezone_description
    ];
  }

  static Future<List<User>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR User.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<User>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <User>[];
    try {
      objList = list
          .map((user) => User.fromMap(user as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR User.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<User>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<User> objList = <User>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = User.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns User by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [User] if exist, otherwise returns null
  Future<User?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    User? obj;
    final data = await _mnUser.getById([id]);
    if (data.length != 0) {
      obj = User.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (User) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnUser.insert(this, ignoreBatch);
    } else {
      await _mnUser.update(this);
    }

    return id;
  }

  /// Saves the (User) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnUser.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnUser.updateOrThrow(this);
    }

    return id;
  }

  /// saveAs User. Returns a new Primary Key value of User

  /// <returns>Returns a new Primary Key value of User
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    id = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<User> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<User> users,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await FlutterTestModel().batchStart();
    for (final obj in users) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await FlutterTestModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < users.length; i++) {
        if (users[i].id == null) {
          users[i].id = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnUser.rawInsert(
          'INSERT OR REPLACE INTO user (id, picture_source, email, title, first, gender, last, street_number, street_name, location_city, location_state, location_contry, coordinate_lat, coordinate_long, date_of_birth, age, registration_age, date_of_registration, phone, cell, id_value, id_name, picture_path, nat, timezone_value, timezone_description)  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
          [
            id,
            picture_source,
            email,
            title,
            first,
            gender,
            last,
            street_number,
            street_name,
            location_city,
            location_state,
            location_contry,
            coordinate_lat,
            coordinate_long,
            date_of_birth,
            age,
            registration_age,
            date_of_registration,
            phone,
            cell,
            id_value,
            id_name,
            picture_path,
            nat,
            timezone_value,
            timezone_description
          ],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true, successMessage: 'User id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'User id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'User Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<User>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<User> users,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnUser.rawInsertAll(
        'INSERT OR REPLACE INTO user (id, picture_source, email, title, first, gender, last, street_number, street_name, location_city, location_state, location_contry, coordinate_lat, coordinate_long, date_of_birth, age, registration_age, date_of_registration, phone, cell, id_value, id_name, picture_path, nat, timezone_value, timezone_description)  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
        users,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes User

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete User invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnUser
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnUser.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [User] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  UserFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return UserFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  UserFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return UserFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    picture_source = picture_source ?? 'network';
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      id = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion user

// region UserField
class UserField extends FilterBase {
  UserField(UserFilterBuilder userFB) : super(userFB);

  @override
  UserFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder isNull() {
    return super.isNull() as UserFilterBuilder;
  }

  @override
  UserFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as UserFilterBuilder;
  }

  @override
  UserFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as UserFilterBuilder;
  }

  @override
  UserField get not {
    return super.not as UserField;
  }
}
// endregion UserField

// region UserFilterBuilder
class UserFilterBuilder extends ConjunctionBase {
  UserFilterBuilder(User obj, bool? getIsDeleted) : super(obj, getIsDeleted) {
    _mnUser = obj._mnUser;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  UserManager? _mnUser;

  /// put the sql keyword 'AND'
  @override
  UserFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  UserFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  UserFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  UserFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  UserFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  UserFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  UserFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  UserFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  UserFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  UserFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  UserFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  UserField _setField(UserField? field, String colName, DbType dbtype) {
    return UserField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  UserField? _id;
  UserField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  UserField? _picture_source;
  UserField get picture_source {
    return _picture_source =
        _setField(_picture_source, 'picture_source', DbType.text);
  }

  UserField? _email;
  UserField get email {
    return _email = _setField(_email, 'email', DbType.text);
  }

  UserField? _title;
  UserField get title {
    return _title = _setField(_title, 'title', DbType.text);
  }

  UserField? _first;
  UserField get first {
    return _first = _setField(_first, 'first', DbType.text);
  }

  UserField? _gender;
  UserField get gender {
    return _gender = _setField(_gender, 'gender', DbType.text);
  }

  UserField? _last;
  UserField get last {
    return _last = _setField(_last, 'last', DbType.text);
  }

  UserField? _street_number;
  UserField get street_number {
    return _street_number =
        _setField(_street_number, 'street_number', DbType.text);
  }

  UserField? _street_name;
  UserField get street_name {
    return _street_name = _setField(_street_name, 'street_name', DbType.text);
  }

  UserField? _location_city;
  UserField get location_city {
    return _location_city =
        _setField(_location_city, 'location_city', DbType.text);
  }

  UserField? _location_state;
  UserField get location_state {
    return _location_state =
        _setField(_location_state, 'location_state', DbType.text);
  }

  UserField? _location_contry;
  UserField get location_contry {
    return _location_contry =
        _setField(_location_contry, 'location_contry', DbType.text);
  }

  UserField? _coordinate_lat;
  UserField get coordinate_lat {
    return _coordinate_lat =
        _setField(_coordinate_lat, 'coordinate_lat', DbType.text);
  }

  UserField? _coordinate_long;
  UserField get coordinate_long {
    return _coordinate_long =
        _setField(_coordinate_long, 'coordinate_long', DbType.text);
  }

  UserField? _date_of_birth;
  UserField get date_of_birth {
    return _date_of_birth =
        _setField(_date_of_birth, 'date_of_birth', DbType.numeric);
  }

  UserField? _age;
  UserField get age {
    return _age = _setField(_age, 'age', DbType.numeric);
  }

  UserField? _registration_age;
  UserField get registration_age {
    return _registration_age =
        _setField(_registration_age, 'registration_age', DbType.numeric);
  }

  UserField? _date_of_registration;
  UserField get date_of_registration {
    return _date_of_registration = _setField(
        _date_of_registration, 'date_of_registration', DbType.numeric);
  }

  UserField? _phone;
  UserField get phone {
    return _phone = _setField(_phone, 'phone', DbType.text);
  }

  UserField? _cell;
  UserField get cell {
    return _cell = _setField(_cell, 'cell', DbType.text);
  }

  UserField? _id_value;
  UserField get id_value {
    return _id_value = _setField(_id_value, 'id_value', DbType.text);
  }

  UserField? _id_name;
  UserField get id_name {
    return _id_name = _setField(_id_name, 'id_name', DbType.text);
  }

  UserField? _picture_path;
  UserField get picture_path {
    return _picture_path =
        _setField(_picture_path, 'picture_path', DbType.text);
  }

  UserField? _nat;
  UserField get nat {
    return _nat = _setField(_nat, 'nat', DbType.text);
  }

  UserField? _timezone_value;
  UserField get timezone_value {
    return _timezone_value =
        _setField(_timezone_value, 'timezone_value', DbType.text);
  }

  UserField? _timezone_description;
  UserField get timezone_description {
    return _timezone_description =
        _setField(_timezone_description, 'timezone_description', DbType.text);
  }

  /// Deletes List<User> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnUser!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnUser!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from user ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnUser!.updateBatch(qparams, values);
  }

  /// This method always returns [User] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> User?
  @override
  Future<User?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnUser!.toList(qparams);
    final data = await objFuture;
    User? obj;
    if (data.isNotEmpty) {
      obj = User.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [User]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> User?
  @override
  Future<User> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        User();
  }

  /// This method returns int. [User]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? userCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final usersFuture = await _mnUser!.toList(qparams);
    final int count = usersFuture[0]['CNT'] as int;
    if (userCount != null) {
      userCount(count);
    }
    return count;
  }

  /// This method returns List<User> [User]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<User>
  @override
  Future<List<User>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<User> usersData = await User.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return usersData;
  }

  /// This method returns Json String [User]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [User]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [User]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnUser!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [User]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM user WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnUser!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [User]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnUser!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await User.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnUser!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion UserFilterBuilder

// region UserFields
class UserFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fPicture_source;
  static TableField get picture_source {
    return _fPicture_source = _fPicture_source ??
        SqlSyntax.setField(_fPicture_source, 'picture_source', DbType.text);
  }

  static TableField? _fEmail;
  static TableField get email {
    return _fEmail =
        _fEmail ?? SqlSyntax.setField(_fEmail, 'email', DbType.text);
  }

  static TableField? _fTitle;
  static TableField get title {
    return _fTitle =
        _fTitle ?? SqlSyntax.setField(_fTitle, 'title', DbType.text);
  }

  static TableField? _fFirst;
  static TableField get first {
    return _fFirst =
        _fFirst ?? SqlSyntax.setField(_fFirst, 'first', DbType.text);
  }

  static TableField? _fGender;
  static TableField get gender {
    return _fGender =
        _fGender ?? SqlSyntax.setField(_fGender, 'gender', DbType.text);
  }

  static TableField? _fLast;
  static TableField get last {
    return _fLast = _fLast ?? SqlSyntax.setField(_fLast, 'last', DbType.text);
  }

  static TableField? _fStreet_number;
  static TableField get street_number {
    return _fStreet_number = _fStreet_number ??
        SqlSyntax.setField(_fStreet_number, 'street_number', DbType.text);
  }

  static TableField? _fStreet_name;
  static TableField get street_name {
    return _fStreet_name = _fStreet_name ??
        SqlSyntax.setField(_fStreet_name, 'street_name', DbType.text);
  }

  static TableField? _fLocation_city;
  static TableField get location_city {
    return _fLocation_city = _fLocation_city ??
        SqlSyntax.setField(_fLocation_city, 'location_city', DbType.text);
  }

  static TableField? _fLocation_state;
  static TableField get location_state {
    return _fLocation_state = _fLocation_state ??
        SqlSyntax.setField(_fLocation_state, 'location_state', DbType.text);
  }

  static TableField? _fLocation_contry;
  static TableField get location_contry {
    return _fLocation_contry = _fLocation_contry ??
        SqlSyntax.setField(_fLocation_contry, 'location_contry', DbType.text);
  }

  static TableField? _fCoordinate_lat;
  static TableField get coordinate_lat {
    return _fCoordinate_lat = _fCoordinate_lat ??
        SqlSyntax.setField(_fCoordinate_lat, 'coordinate_lat', DbType.text);
  }

  static TableField? _fCoordinate_long;
  static TableField get coordinate_long {
    return _fCoordinate_long = _fCoordinate_long ??
        SqlSyntax.setField(_fCoordinate_long, 'coordinate_long', DbType.text);
  }

  static TableField? _fDate_of_birth;
  static TableField get date_of_birth {
    return _fDate_of_birth = _fDate_of_birth ??
        SqlSyntax.setField(_fDate_of_birth, 'date_of_birth', DbType.numeric);
  }

  static TableField? _fAge;
  static TableField get age {
    return _fAge = _fAge ?? SqlSyntax.setField(_fAge, 'age', DbType.numeric);
  }

  static TableField? _fRegistration_age;
  static TableField get registration_age {
    return _fRegistration_age = _fRegistration_age ??
        SqlSyntax.setField(
            _fRegistration_age, 'registration_age', DbType.numeric);
  }

  static TableField? _fDate_of_registration;
  static TableField get date_of_registration {
    return _fDate_of_registration = _fDate_of_registration ??
        SqlSyntax.setField(
            _fDate_of_registration, 'date_of_registration', DbType.numeric);
  }

  static TableField? _fPhone;
  static TableField get phone {
    return _fPhone =
        _fPhone ?? SqlSyntax.setField(_fPhone, 'phone', DbType.text);
  }

  static TableField? _fCell;
  static TableField get cell {
    return _fCell = _fCell ?? SqlSyntax.setField(_fCell, 'cell', DbType.text);
  }

  static TableField? _fId_value;
  static TableField get id_value {
    return _fId_value =
        _fId_value ?? SqlSyntax.setField(_fId_value, 'id_value', DbType.text);
  }

  static TableField? _fId_name;
  static TableField get id_name {
    return _fId_name =
        _fId_name ?? SqlSyntax.setField(_fId_name, 'id_name', DbType.text);
  }

  static TableField? _fPicture_path;
  static TableField get picture_path {
    return _fPicture_path = _fPicture_path ??
        SqlSyntax.setField(_fPicture_path, 'picture_path', DbType.text);
  }

  static TableField? _fNat;
  static TableField get nat {
    return _fNat = _fNat ?? SqlSyntax.setField(_fNat, 'nat', DbType.text);
  }

  static TableField? _fTimezone_value;
  static TableField get timezone_value {
    return _fTimezone_value = _fTimezone_value ??
        SqlSyntax.setField(_fTimezone_value, 'timezone_value', DbType.text);
  }

  static TableField? _fTimezone_description;
  static TableField get timezone_description {
    return _fTimezone_description = _fTimezone_description ??
        SqlSyntax.setField(
            _fTimezone_description, 'timezone_description', DbType.text);
  }
}
// endregion UserFields

//region UserManager
class UserManager extends SqfEntityProvider {
  UserManager()
      : super(FlutterTestModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'user';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion UserManager
class FlutterTestModelSequenceManager extends SqfEntityProvider {
  FlutterTestModelSequenceManager() : super(FlutterTestModel());
}
// END OF ENTITIES
